### ISSUE TITLE
Sitemap generation is broken on Django 4.2

### ISSUE THREAD

**Issue by stevejalim** [mozmeao/www-sitemap-generator#6]
The sitemap generation uses the Bedrock image, but [it looks like](https://github.com/mozmeao/www-sitemap-generator/actions/runs/8588558133/job/23533582471#step:4:310) things are breaking related to clashing old-style vs new-style settings:

`django.core.exceptions.ImproperlyConfigured: STATICFILES_STORAGE/STORAGES are mutually exclusive.`

**Comment by robhudson** [comment]
https://github.com/mozmeao/www-sitemap-generator/pull/7

**Comment by robhudson** [comment]
Fixed in https://github.com/mozmeao/www-sitemap-generator/pull/7
